# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MODemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MODemo
  pod 'Masonry'
  pod 'SnapKit', '~> 5.6.0'
  pod 'lottie-ios'

  target 'MODemoTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.8.1'
    pod 'OCHamcrest', '~> 8.0'
    # Pods for testing
  end

  target 'MODemoUITests' do
    # Pods for testing
  end

end
