# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MODemoOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MODemoOC

  target 'MODemoOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MODemoOCUITests' do
    # Pods for testing
  end

end
