# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MODemoOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  # Pods for MODemoOC

  target 'MODemoOCTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.8.1'
    pod 'OCHamcrest', '~> 8.0'
    # Pods for testing
  end

  target 'MODemoOCUITests' do
    # Pods for testing
  end

end
